"""Small stable-worldmodel-compatible cost module for LE-WM smoke training."""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any

from offroad_sim.utils.runtime_env import prepare_stable_worldmodel_runtime


prepare_stable_worldmodel_runtime()
import torch


@dataclass(slots=True)
class LeWMCostModelConfig:
    dt: float = 0.1
    steer_gain: float = 0.08
    throttle_gain: float = 0.2
    brake_gain: float = 0.4
    goal_weight: float = 1.0
    progress_weight: float = 0.25
    smoothness_weight: float = 0.08
    action_weight: float = 0.04


class LeWMCostModel(torch.nn.Module):
    """Torch module exposing `get_cost(info_dict, candidates)` for CEMSolver.

    It is intentionally compact: training estimates a few dynamics scalars from
    exported trajectories, then stable-worldmodel handles CEM over this module.
    The class lives in an importable module so `torch.load(..., weights_only=False)`
    can deserialize checkpoints generated by `scripts/train_lewm_cost_model.py`.
    """

    def __init__(self, config: LeWMCostModelConfig | None = None, metadata: dict[str, Any] | None = None) -> None:
        super().__init__()
        self.config = config or LeWMCostModelConfig()
        self.metadata = dict(metadata or {})

    def get_cost(self, info_dict: dict[str, torch.Tensor], candidates: torch.Tensor) -> torch.Tensor:
        state = _select_state(info_dict.get("state"), candidates)
        goal = _select_goal(info_dict.get("goal_state"), state)
        actions = torch.clamp(candidates.float(), torch.tensor([-1.0, 0.0, 0.0], device=candidates.device), torch.tensor([1.0, 1.0, 1.0], device=candidates.device))

        x = state[..., 0]
        y = state[..., 1]
        yaw = state[..., 2]
        speed = state[..., 3].clamp_min(0.0)
        start_distance = torch.linalg.vector_norm(torch.stack([x - goal[..., 0], y - goal[..., 1]], dim=-1), dim=-1)

        for step in range(actions.shape[2]):
            steer = actions[:, :, step, 0]
            throttle = actions[:, :, step, 1]
            brake = actions[:, :, step, 2]
            speed = torch.clamp(speed + self.config.throttle_gain * throttle - self.config.brake_gain * brake, min=0.0)
            yaw = yaw + self.config.steer_gain * steer
            x = x + speed * torch.cos(yaw) * self.config.dt
            y = y + speed * torch.sin(yaw) * self.config.dt

        final_distance = torch.linalg.vector_norm(torch.stack([x - goal[..., 0], y - goal[..., 1]], dim=-1), dim=-1)
        progress = start_distance - final_distance
        smoothness = torch.mean(torch.abs(actions[:, :, 1:, :] - actions[:, :, :-1, :]), dim=(2, 3)) if actions.shape[2] > 1 else torch.zeros_like(final_distance)
        effort = torch.mean(torch.abs(actions), dim=(2, 3))
        return (
            self.config.goal_weight * final_distance
            - self.config.progress_weight * progress
            + self.config.smoothness_weight * smoothness
            + self.config.action_weight * effort
        )

    def to_metadata(self) -> dict[str, Any]:
        return {"config": asdict(self.config), "metadata": self.metadata}


def _select_state(value: torch.Tensor | None, candidates: torch.Tensor) -> torch.Tensor:
    batch, samples = candidates.shape[:2]
    if value is None:
        return torch.zeros((batch, samples, 4), dtype=candidates.dtype, device=candidates.device)
    value = value.to(device=candidates.device, dtype=candidates.dtype)
    if value.ndim == 4:
        state = value[:, :, -1, :]
    elif value.ndim == 3:
        state = value[:, -1, :].unsqueeze(1)
    elif value.ndim == 2:
        state = value.unsqueeze(1)
    else:
        state = torch.zeros((batch, 1, 4), dtype=candidates.dtype, device=candidates.device)
    return state.expand(batch, samples, 4)


def _select_goal(value: torch.Tensor | None, state: torch.Tensor) -> torch.Tensor:
    if value is None:
        return torch.zeros((*state.shape[:2], 2), dtype=state.dtype, device=state.device)
    value = value.to(device=state.device, dtype=state.dtype)
    if value.ndim == 4:
        goal = value[:, :, -1, :]
    elif value.ndim == 3:
        goal = value[:, -1, :].unsqueeze(1)
    elif value.ndim == 2:
        goal = value.unsqueeze(1)
    else:
        goal = torch.zeros((*state.shape[:2], 2), dtype=state.dtype, device=state.device)
    return goal[..., :2].expand(*state.shape[:2], 2)
